name: 'dbt_velibdata'
version: '1.0.0'
profile: 'dbt_velibdata'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_velibdata:
    staging:
      +materialized: view
      +schema: silver
    intermediate:
      +materialized: table
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
